name: Cypress Tests

on:
  workflow_dispatch:

  push:
    branches: [master]
  
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: windows-latest
    name: E2E on Chrome
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
        continue-on-error: true
       
      - uses: actions/upload-artifact@v4
        # add the line below to store screenshots only on failures
        # if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
      - uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
