name: Cypress Tests

on:
  workflow_dispatch:

  push:
    branches: [master]
  
  pull_request:
    branches: [master]
  
jobs:

  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    name: E2E on Chrome

    strategy:
      fail-fast: false 
      matrix:
        containers: [1, 2, 3, 4]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          record: true
          parallel: true 
        env:
          group: 'UI-Chrome'
          TZ: Europe/Warsaw
          CYPRESS_ENV: Poland
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Screenshots report
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore 
        
      - name: Video report  
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore 

