name: Cypress Tests

on:
  workflow_dispatch:

  push:
    branches: [master]
  
  pull_request:
    branches: [master]

# jobs:
#   test:
#     timeout-minutes: 60
#     runs-on: ubuntu-22.04
#    
#     steps:
    
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    name: E2E on Chrome
    # Runs tests in parallel with matrix strategy https://docs.cypress.io/guides/guides/parallelization
    # https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs
    # Also see warning here https://github.com/cypress-io/github-action#parallel
    strategy:
      fail-fast: false # https://github.com/cypress-io/github-action/issues/48
      matrix:
        containers: [1, 2, 3, 4, 5] # Uses 2 parallel instances
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        # Uses the official Cypress GitHub action https://github.com/cypress-io/github-action
        uses: cypress-io/github-action@v6
        with:
          # Starts web server for E2E tests - replace with your own server invocation
          # https://docs.cypress.io/guides/continuous-integration/introduction#Boot-your-server
          browser: chrome
          # start: npm start
          wait-on: 'http://localhost:3000' # Waits for above
          # Records to Cypress Cloud
          # https://docs.cypress.io/guides/cloud/projects#Set-up-a-project-to-record
          record: true
          parallel: true # Runs test in parallel using settings above
        env:
          TZ: Europe/Warsaw
          CYPRESS_ENV: Poland
          # For recording and parallelization to work you must set your CYPRESS_RECORD_KEY
          # in GitHub repo → Settings → Secrets → Actions
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # Creating a token https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Checkout
        # uses: actions/checkout@v4
        
      # - name: Cypress run
        # uses: cypress-io/github-action@v6
        # with:
          # browser: chrome
        # continue-on-error: true
        # env:
          # TZ: Europe/Warsaw
          # CYPRESS_ENV: Poland
       
      - name: Screenshots report
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore 
        
      - name: Video report  
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore 

