name: Cypress Tests

on:
  workflow_dispatch:

  push:
    branches: [master]
  
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-22.04
    name: E2E on Chrome
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
        continue-on-error: true
       
      - name: Screenshots report
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore 
        
      - name: Video report  
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore 
